import 'package:flutter/material.dart';

enum DesignPreviewKind {
  dashboard,
  form,
  list,
  detail,
  conversation,
  canvas,
  game,
  settings,
}

@immutable
class DesignScreenDefinition {
  const DesignScreenDefinition({
    required this.id,
    required this.className,
    required this.category,
    required this.icon,
    required this.subtitle,
    required this.kind,
    required this.primaryItems,
    required this.secondaryItems,
    required this.actions,
  });

  final String id;
  final String className;
  final String category;
  final IconData icon;
  final String subtitle;
  final DesignPreviewKind kind;
  final List<String> primaryItems;
  final List<String> secondaryItems;
  final List<String> actions;

  String get displayName {
    final withoutDesign = className.replaceAll('Design', '');
    return withoutDesign.replaceAllMapped(
      RegExp(r'(?<=[a-z0-9])(?=[A-Z])'),
      (_) => ' ',
    );
  }
}

const designScreenDefinitions = <DesignScreenDefinition>[
  DesignScreenDefinition(
    id: 'home',
    className: 'HomeDesignScreen',
    category: 'Foundation',
    icon: Icons.home_outlined,
    subtitle:
        'A living office map with quick access to Coach, Events, and People.',
    kind: DesignPreviewKind.game,
    primaryItems: ['Coach', 'Office map', 'Arcade'],
    secondaryItems: ['Colleague positions', 'Recent case', 'Daily motto'],
    actions: ['Move around office', 'Ask for advice'],
  ),
  DesignScreenDefinition(
    id: 'splash',
    className: 'SplashDesignScreen',
    category: 'Foundation',
    icon: Icons.auto_awesome_rounded,
    subtitle: 'A calm first impression while the workspace wakes up.',
    kind: DesignPreviewKind.detail,
    primaryItems: ['Animated mark', 'Loading progress', 'Offline fallback'],
    secondaryItems: ['Version label', 'Secure workspace message'],
    actions: ['Retry'],
  ),
  DesignScreenDefinition(
    id: 'language-setup',
    className: 'LanguageSetupDesignScreen',
    category: 'Foundation',
    icon: Icons.translate_rounded,
    subtitle: 'Choose the language used across coaching and the interface.',
    kind: DesignPreviewKind.form,
    primaryItems: ['English', '简体中文', '繁體中文'],
    secondaryItems: ['System language detected', 'Change anytime'],
    actions: ['Continue'],
  ),
  DesignScreenDefinition(
    id: 'privacy-notice',
    className: 'PrivacyNoticeDesignScreen',
    category: 'Foundation',
    icon: Icons.shield_outlined,
    subtitle: 'Clear first-use guidance before workplace material is entered.',
    kind: DesignPreviewKind.detail,
    primaryItems: [
      'Use fake colleague names',
      'Avoid confidential material',
      'AI provider consent',
    ],
    secondaryItems: ['Data retention', 'Provider details'],
    actions: ['I understand', 'Review policy'],
  ),
  DesignScreenDefinition(
    id: 'name-setup',
    className: 'NameSetupDesignScreen',
    category: 'Foundation',
    icon: Icons.edit_rounded,
    subtitle: 'Choose a private display name of no more than 15 characters.',
    kind: DesignPreviewKind.form,
    primaryItems: ['Display name', 'Live character count', 'Avatar preview'],
    secondaryItems: ['15-character limit', 'Change later'],
    actions: ['Continue'],
  ),
  DesignScreenDefinition(
    id: 'auth',
    className: 'AuthDesignScreen',
    category: 'Foundation',
    icon: Icons.lock_open_rounded,
    subtitle:
        'Choose anonymous, email, Google, or Apple Firebase authentication.',
    kind: DesignPreviewKind.form,
    primaryItems: ['Anonymous', 'Email and password', 'Google', 'Apple'],
    secondaryItems: ['Validation feedback', 'Restore workspace'],
    actions: ['Continue'],
  ),
  DesignScreenDefinition(
    id: 'account',
    className: 'AccountDesignScreen',
    category: 'Foundation',
    icon: Icons.person_outline_rounded,
    subtitle: 'Profile, subscription, language, and account controls.',
    kind: DesignPreviewKind.settings,
    primaryItems: ['Profile', 'Language', 'Subscription'],
    secondaryItems: ['Export data', 'Sign out', 'Delete account'],
    actions: ['Save changes'],
  ),
  DesignScreenDefinition(
    id: 'paywall',
    className: 'PaywallDesignScreen',
    category: 'Foundation',
    icon: Icons.workspace_premium_outlined,
    subtitle: 'A transparent comparison of free and premium coaching.',
    kind: DesignPreviewKind.dashboard,
    primaryItems: ['Monthly plan', 'Annual plan', 'Feature comparison'],
    secondaryItems: ['Restore purchase', 'Earned premium pass'],
    actions: ['Start premium', 'Restore'],
  ),
  DesignScreenDefinition(
    id: 'workspace-setup',
    className: 'WorkspaceSetupDesignScreen',
    category: 'Case File',
    icon: Icons.business_center_outlined,
    subtitle: 'Set the workplace context that shapes every recommendation.',
    kind: DesignPreviewKind.form,
    primaryItems: ['Your role', 'Organization', 'Primary goals'],
    secondaryItems: ['Constraints', 'Reporting line', 'Industry'],
    actions: ['Save workspace', 'Skip for now'],
  ),
  DesignScreenDefinition(
    id: 'people-network',
    className: 'PeopleNetworkDesignScreen',
    category: 'Case File',
    icon: Icons.hub_rounded,
    subtitle:
        'Explore moving colleagues, personas, and pairwise relationships in one space.',
    kind: DesignPreviewKind.canvas,
    primaryItems: ['Moving avatars', 'Persona panel', 'Relationship gesture'],
    secondaryItems: ['Collision regions', 'Recorded events', 'Current dynamic'],
    actions: ['Modify persona', 'Modify relationship'],
  ),
  DesignScreenDefinition(
    id: 'character-editor',
    className: 'CharacterEditorDesignScreen',
    category: 'Case File',
    icon: Icons.person_add_alt_1_rounded,
    subtitle:
        'Edit colleague details, then record their relationship with you before opening Face Lab.',
    kind: DesignPreviewKind.form,
    primaryItems: [
      'Colleague details',
      'Relationship with you',
      'Five-level score',
    ],
    secondaryItems: [
      'Politics consultant analysis',
      'Major events',
      'Current dynamic',
    ],
    actions: ['Analyze details', 'Open Face Lab'],
  ),
  DesignScreenDefinition(
    id: 'face-lab',
    className: 'FaceLabDesignScreen',
    category: 'Case File',
    icon: Icons.face_retouching_natural_rounded,
    subtitle:
        'Create memorable parametric cartoon avatars for the user and colleagues.',
    kind: DesignPreviewKind.canvas,
    primaryItems: ['User avatar', 'First colleague', 'Head', 'Hair'],
    secondaryItems: ['Brows', 'Accessories', 'Expression'],
    actions: ['Randomize', 'Save avatar'],
  ),
  DesignScreenDefinition(
    id: 'character-profile',
    className: 'CharacterProfileDesignScreen',
    category: 'Case File',
    icon: Icons.badge_outlined,
    subtitle:
        'Review a person’s complete recorded information, persona, relationships, and related events.',
    kind: DesignPreviewKind.detail,
    primaryItems: [
      'Avatar and persona',
      'Workspace information',
      'Related events',
    ],
    secondaryItems: [
      'Self plus colleagues',
      'Relationship with user',
      'Evidence confidence',
    ],
    actions: ['Select person', 'Modify relationship'],
  ),
  DesignScreenDefinition(
    id: 'relationship-editor',
    className: 'RelationshipEditorDesignScreen',
    category: 'Case File',
    icon: Icons.device_hub_rounded,
    subtitle:
        'Create or modify user-colleague and colleague-colleague relationships.',
    kind: DesignPreviewKind.form,
    primaryItems: ['Two avatars and personas', 'Shared work', 'Major events'],
    secondaryItems: [
      'Current dynamic',
      'Five-level score',
      'Four preview modes',
    ],
    actions: ['Analyze relationship', 'Create or save'],
  ),
  DesignScreenDefinition(
    id: 'event-timeline',
    className: 'EventTimelineDesignScreen',
    category: 'Case File',
    icon: Icons.timeline_rounded,
    subtitle:
        'Browse workplace events chronologically and open any event for inspection.',
    kind: DesignPreviewKind.list,
    primaryItems: ['Chronological cards', 'Date and time', 'Participants'],
    secondaryItems: ['Impact color', 'Involving-you filter', 'Event summary'],
    actions: ['Inspect event', 'Add event'],
  ),
  DesignScreenDefinition(
    id: 'event-editor',
    className: 'EventEditorDesignScreen',
    category: 'Case File',
    icon: Icons.edit_calendar_outlined,
    subtitle:
        'Inspect or create an event with LLM-assisted facts, feelings, and quantified estimates.',
    kind: DesignPreviewKind.form,
    primaryItems: ['Date and time', 'Involved people', 'Detailed story'],
    secondaryItems: [
      'Personal feeling',
      'Impact',
      'Stress',
      'Urgency',
      'Evidence',
    ],
    actions: ['Analyze free text', 'Create or save event'],
  ),
  DesignScreenDefinition(
    id: 'artifact-viewer',
    className: 'ArtifactViewerDesignScreen',
    category: 'Case File',
    icon: Icons.description_outlined,
    subtitle: 'Inspect source material beside extracted text and provenance.',
    kind: DesignPreviewKind.detail,
    primaryItems: ['Source preview', 'Extracted text', 'Linked claims'],
    secondaryItems: ['Retention date', 'OCR confidence', 'Provenance'],
    actions: ['Edit text', 'Delete artifact'],
  ),
  DesignScreenDefinition(
    id: 'advice-input',
    className: 'AdviceInputDesignScreen',
    category: 'Coach',
    icon: Icons.psychology_alt_outlined,
    subtitle:
        'Bring together the question, goal, people, and relevant history.',
    kind: DesignPreviewKind.form,
    primaryItems: [
      'What happened?',
      'What outcome do you want?',
      'People involved',
    ],
    secondaryItems: ['Select events', 'Add image', 'Use voice'],
    actions: ['Analyze situation', 'Save draft'],
  ),
  DesignScreenDefinition(
    id: 'image-capture',
    className: 'ImageCaptureDesignScreen',
    category: 'Coach',
    icon: Icons.document_scanner_outlined,
    subtitle: 'Frame and improve a screenshot or camera image before OCR.',
    kind: DesignPreviewKind.canvas,
    primaryItems: ['Camera preview', 'Crop handles', 'Perspective guides'],
    secondaryItems: ['Rotate', 'Contrast', 'Gallery'],
    actions: ['Use image', 'Retake'],
  ),
  DesignScreenDefinition(
    id: 'ocr-review',
    className: 'OcrReviewDesignScreen',
    category: 'Coach',
    icon: Icons.text_snippet_outlined,
    subtitle: 'Correct recognized email text before it becomes case context.',
    kind: DesignPreviewKind.detail,
    primaryItems: ['Image region', 'Editable text', 'Email thread order'],
    secondaryItems: [
      'Confidence',
      'Remove irrelevant text',
      'Optional redaction',
    ],
    actions: ['Use this text', 'Scan again'],
  ),
  DesignScreenDefinition(
    id: 'voice-input',
    className: 'VoiceInputDesignScreen',
    category: 'Coach',
    icon: Icons.graphic_eq_rounded,
    subtitle: 'Capture a short spoken account with a visible 55-second limit.',
    kind: DesignPreviewKind.conversation,
    primaryItems: ['Live waveform', '00:37 remaining', 'Live transcript'],
    secondaryItems: ['Locale', 'Continue segment', 'Correction'],
    actions: ['Finish', 'Pause'],
  ),
  DesignScreenDefinition(
    id: 'advice-result',
    className: 'AdviceResultDesignScreen',
    category: 'Coach',
    icon: Icons.lightbulb_outline_rounded,
    subtitle: 'Separate observations, unknowns, hypotheses, and safe options.',
    kind: DesignPreviewKind.detail,
    primaryItems: [
      'What we observed',
      'Possible explanations',
      'Recommended next step',
    ],
    secondaryItems: ['Evidence', 'Risks', 'Message script', 'Confidence'],
    actions: ['Compare replies', 'Save advice'],
  ),
  DesignScreenDefinition(
    id: 'reply-simulator-input',
    className: 'ReplySimulatorInputDesignScreen',
    category: 'Coach',
    icon: Icons.alt_route_rounded,
    subtitle: 'Test different replies against the same incoming message.',
    kind: DesignPreviewKind.form,
    primaryItems: ['Incoming email', 'Reply A', 'Reply B'],
    secondaryItems: ['Reply C', 'Primary goal', 'Risk tolerance'],
    actions: ['Simulate outcomes', 'Draft another reply'],
  ),
  DesignScreenDefinition(
    id: 'reply-simulator-result',
    className: 'ReplySimulatorResultDesignScreen',
    category: 'Coach',
    icon: Icons.account_tree_outlined,
    subtitle:
        'Compare likely reactions, warning signs, and harm across options.',
    kind: DesignPreviewKind.dashboard,
    primaryItems: [
      'Reply A · De-escalates',
      'Reply B · Clarifies',
      'Reply C · Delays',
    ],
    secondaryItems: ['Likely reaction', 'Warning indicators', 'Reversibility'],
    actions: ['Use recommended reply', 'Edit options'],
  ),
  DesignScreenDefinition(
    id: 'prediction-outcome',
    className: 'PredictionOutcomeDesignScreen',
    category: 'Coach',
    icon: Icons.fact_check_outlined,
    subtitle: 'Record reality and compare it with the predicted branches.',
    kind: DesignPreviewKind.form,
    primaryItems: [
      'What happened?',
      'Closest prediction',
      'Unexpected response',
    ],
    secondaryItems: ['Impact', 'New evidence', 'Relationship change'],
    actions: ['Save outcome', 'Update case'],
  ),
  DesignScreenDefinition(
    id: 'roleplay-setup',
    className: 'RoleplaySetupDesignScreen',
    category: 'Coach',
    icon: Icons.theater_comedy_outlined,
    subtitle: 'Prepare a realistic practice conversation with clear goals.',
    kind: DesignPreviewKind.form,
    primaryItems: ['Choose person', 'Conversation goal', 'Tone'],
    secondaryItems: ['Difficulty', 'Known objections', 'Success condition'],
    actions: ['Start roleplay'],
  ),
  DesignScreenDefinition(
    id: 'roleplay-session',
    className: 'RoleplaySessionDesignScreen',
    category: 'Coach',
    icon: Icons.forum_outlined,
    subtitle:
        'Practice through realistic turns without risking the real relationship.',
    kind: DesignPreviewKind.conversation,
    primaryItems: [
      'Colleague response',
      'Your response',
      'Conversation progress',
    ],
    secondaryItems: ['Voice reply', 'Text reply', 'Pause'],
    actions: ['Send response', 'End practice'],
  ),
  DesignScreenDefinition(
    id: 'roleplay-feedback',
    className: 'RoleplayFeedbackDesignScreen',
    category: 'Coach',
    icon: Icons.rate_review_outlined,
    subtitle: 'Review clarity, evidence, boundaries, and avoidable risk.',
    kind: DesignPreviewKind.dashboard,
    primaryItems: [
      'Clarity · Strong',
      'Evidence · Improve',
      'Boundaries · Clear',
    ],
    secondaryItems: ['Risky phrase', 'Stronger alternative', 'Coach notes'],
    actions: ['Retry conversation', 'Save feedback'],
  ),
  DesignScreenDefinition(
    id: 'advice-history',
    className: 'AdviceHistoryDesignScreen',
    category: 'Coach',
    icon: Icons.history_rounded,
    subtitle: 'Find previous advice, scripts, predictions, and outcomes.',
    kind: DesignPreviewKind.list,
    primaryItems: [
      'Budget email · Today',
      'Review preparation · Monday',
      'Scope dispute · Aug 28',
    ],
    secondaryItems: ['Saved scripts', 'Outcome recorded', 'Filter by person'],
    actions: ['Search history', 'New question'],
  ),
  DesignScreenDefinition(
    id: 'office-map-list',
    className: 'OfficeMapListDesignScreen',
    category: 'Office & Knowledge',
    icon: Icons.map_outlined,
    subtitle: 'Choose an office layout or begin from a useful template.',
    kind: DesignPreviewKind.list,
    primaryItems: ['Main office', 'Project room', 'Remote team'],
    secondaryItems: ['Last edited', 'People seated', 'Templates'],
    actions: ['New office map', 'Use template'],
  ),
  DesignScreenDefinition(
    id: 'office-map-editor',
    className: 'OfficeMapEditorDesignScreen',
    category: 'Office & Knowledge',
    icon: Icons.dashboard_customize_outlined,
    subtitle:
        'Build the same isometric office used by Home with draggable furniture, partitions, and characters.',
    kind: DesignPreviewKind.canvas,
    primaryItems: ['Desk', 'Partition', 'Meeting room', 'Character seat'],
    secondaryItems: ['Zoom', 'Undo', 'Layers', 'Selection'],
    actions: ['Save layout', 'Preview'],
  ),
  DesignScreenDefinition(
    id: 'office-character-panel',
    className: 'OfficeCharacterPanelDesignScreen',
    category: 'Office & Knowledge',
    icon: Icons.person_pin_circle_outlined,
    subtitle: 'Open useful person context directly from their office seat.',
    kind: DesignPreviewKind.detail,
    primaryItems: ['Morgan · Manager', 'Seat B12', 'Recent interaction'],
    secondaryItems: ['Relationship', 'Open events', 'Start simulation'],
    actions: ['View profile', 'Ask about Morgan'],
  ),
  DesignScreenDefinition(
    id: 'business-outlook',
    className: 'BusinessOutlookDesignScreen',
    category: 'Office & Knowledge',
    icon: Icons.trending_up_rounded,
    subtitle: 'Connect cited macro movement to possible internal pressure.',
    kind: DesignPreviewKind.dashboard,
    primaryItems: ['Demand outlook', 'Cost pressure', 'Regulatory movement'],
    secondaryItems: ['Source age', 'Confidence', 'Business impact'],
    actions: ['Refresh outlook', 'View sources'],
  ),
  DesignScreenDefinition(
    id: 'industry-profile',
    className: 'IndustryProfileDesignScreen',
    category: 'Office & Knowledge',
    icon: Icons.factory_outlined,
    subtitle: 'Describe the market forces surrounding the organization.',
    kind: DesignPreviewKind.form,
    primaryItems: ['Industry', 'Operating countries', 'Products'],
    secondaryItems: ['Customers', 'Competitors', 'Regulation', 'Ticker'],
    actions: ['Save profile'],
  ),
  DesignScreenDefinition(
    id: 'motto-feed',
    className: 'MottoFeedDesignScreen',
    category: 'Office & Knowledge',
    icon: Icons.format_quote_rounded,
    subtitle: 'Offer timely, referenced perspective without empty slogans.',
    kind: DesignPreviewKind.detail,
    primaryItems: ['Motto', 'Source and chapter', 'Office interpretation'],
    secondaryItems: ['Misuse warning', 'Why this appears now'],
    actions: ['Save motto', 'Next motto'],
  ),
  DesignScreenDefinition(
    id: 'motto-library',
    className: 'MottoLibraryDesignScreen',
    category: 'Office & Knowledge',
    icon: Icons.menu_book_outlined,
    subtitle: 'Browse verified wisdom by theme, source, and situation.',
    kind: DesignPreviewKind.list,
    primaryItems: ['Preparation', 'Restraint', 'Self-knowledge'],
    secondaryItems: ['Favorites', 'Source filter', 'Search'],
    actions: ['Browse favorites', 'Search mottos'],
  ),
  DesignScreenDefinition(
    id: 'scenario-library',
    className: 'ScenarioLibraryDesignScreen',
    category: 'Office & Knowledge',
    icon: Icons.library_books_outlined,
    subtitle: 'Explore sourced workplace patterns and documented cases.',
    kind: DesignPreviewKind.list,
    primaryItems: ['Credit theft', 'Information hoarding', 'Review politics'],
    secondaryItems: ['Evidence tier', 'Industry', 'Culture', 'Source type'],
    actions: ['Search scenarios', 'Open filters'],
  ),
  DesignScreenDefinition(
    id: 'scenario-detail',
    className: 'ScenarioDetailDesignScreen',
    category: 'Office & Knowledge',
    icon: Icons.chrome_reader_mode_outlined,
    subtitle:
        'Understand signals, alternatives, outcomes, and useful responses.',
    kind: DesignPreviewKind.detail,
    primaryItems: ['Pattern and actors', 'Timeline', 'Observable signals'],
    secondaryItems: ['Alternative explanations', 'Actual outcome', 'Citations'],
    actions: ['Apply to my case', 'View source'],
  ),
  DesignScreenDefinition(
    id: 'arcade',
    className: 'ArcadeDesignScreen',
    category: 'Arcade',
    icon: Icons.sports_esports_rounded,
    subtitle: 'A bright fictional arcade hub for skill contests and rewards.',
    kind: DesignPreviewKind.game,
    primaryItems: ['Slap Desk', 'Credit Chase', 'Rumour Flip', '5pm Ghost'],
    secondaryItems: ['Daily contest', 'Premium pass', 'Personal best'],
    actions: ['Play featured game', 'View contests'],
  ),
  DesignScreenDefinition(
    id: 'slap-desk',
    className: 'SlapDeskDesignScreen',
    category: 'Arcade',
    icon: Icons.back_hand_outlined,
    subtitle:
        'Dash through a fictional floor and keep the correct-target combo.',
    kind: DesignPreviewKind.game,
    primaryItems: ['Arena', 'Target card', 'Combo meter'],
    secondaryItems: ['Joystick', 'Dash', 'Timer', 'Score'],
    actions: ['Start run', 'Restart run'],
  ),
  DesignScreenDefinition(
    id: 'credit-chase',
    className: 'CreditChaseDesignScreen',
    category: 'Arcade',
    icon: Icons.stars_rounded,
    subtitle: 'Trace stolen tokens and catch them before they disappear.',
    kind: DesignPreviewKind.game,
    primaryItems: ['Moving colleagues', 'Credit trail', 'Catch meter'],
    secondaryItems: ['Trace', 'Yank', 'Timer', 'Score'],
    actions: ['Start chase', 'Restart chase'],
  ),
  DesignScreenDefinition(
    id: 'rumour-flip',
    className: 'RumourFlipDesignScreen',
    category: 'Arcade',
    icon: Icons.flip_camera_android_rounded,
    subtitle: 'Flick fictional rumor bubbles into exaggerated honest subtext.',
    kind: DesignPreviewKind.game,
    primaryItems: ['Rumor bubble', 'Honest subtext', 'Listener mood'],
    secondaryItems: ['Flick control', 'Combo', 'Timer', 'Score'],
    actions: ['Start flipping', 'Restart run'],
  ),
  DesignScreenDefinition(
    id: 'five-pm-ghost',
    className: 'FivePmGhostDesignScreen',
    category: 'Arcade',
    icon: Icons.visibility_outlined,
    subtitle: 'Dodge vision cones and escape the fictional late meeting.',
    kind: DesignPreviewKind.game,
    primaryItems: ['Vision cones', 'Office obstacles', 'Exit route'],
    secondaryItems: ['Near miss', 'Slow-mo', 'Timer', 'Score'],
    actions: ['Start escape', 'Restart escape'],
  ),
  DesignScreenDefinition(
    id: 'contest-list',
    className: 'ContestListDesignScreen',
    category: 'Arcade',
    icon: Icons.military_tech_outlined,
    subtitle: 'Choose daily, weekly, or monthly skill contests.',
    kind: DesignPreviewKind.list,
    primaryItems: ['Daily dash', 'Weekly chase', 'Monthly master'],
    secondaryItems: ['Time left', 'Entry status', 'Premium prize'],
    actions: ['Enter contest', 'View rules'],
  ),
  DesignScreenDefinition(
    id: 'leaderboard',
    className: 'LeaderboardDesignScreen',
    category: 'Arcade',
    icon: Icons.leaderboard_outlined,
    subtitle: 'Show score-only rankings and the player’s progress.',
    kind: DesignPreviewKind.list,
    primaryItems: ['1 · 128,420', '2 · 121,050', 'You · 98,700'],
    secondaryItems: ['Season', 'Friends', 'Personal best'],
    actions: ['Change contest', 'Play now'],
  ),
  DesignScreenDefinition(
    id: 'rewarded-ad-offer',
    className: 'RewardedAdOfferDesignScreen',
    category: 'Arcade',
    icon: Icons.ondemand_video_outlined,
    subtitle: 'Offer an optional, clearly capped in-game advantage.',
    kind: DesignPreviewKind.dashboard,
    primaryItems: ['Continue run', '+15 seconds', 'Reveal patrol'],
    secondaryItems: ['Daily cap', 'No leaderboard penalty', 'Skip'],
    actions: ['Watch ad', 'No thanks'],
  ),
  DesignScreenDefinition(
    id: 'premium-pass',
    className: 'PremiumPassDesignScreen',
    category: 'Arcade',
    icon: Icons.card_membership_rounded,
    subtitle: 'Show earned Coach access and its exact expiry.',
    kind: DesignPreviewKind.detail,
    primaryItems: ['7-day pass', 'Expires Sep 18', 'Unlocked features'],
    secondaryItems: ['How it was earned', 'Next contest'],
    actions: ['Open Coach', 'View contests'],
  ),
  DesignScreenDefinition(
    id: 'settings',
    className: 'SettingsDesignScreen',
    category: 'Settings',
    icon: Icons.tune_rounded,
    subtitle: 'Control language, appearance, AI, data, and accessibility.',
    kind: DesignPreviewKind.settings,
    primaryItems: ['Language', 'Appearance', 'Notifications'],
    secondaryItems: ['AI provider', 'Data controls', 'Accessibility', 'Legal'],
    actions: ['Save settings'],
  ),
  DesignScreenDefinition(
    id: 'data-controls',
    className: 'DataControlsDesignScreen',
    category: 'Settings',
    icon: Icons.storage_rounded,
    subtitle: 'Make retention, export, deletion, and consent understandable.',
    kind: DesignPreviewKind.settings,
    primaryItems: ['Retention period', 'Export archive', 'Consent history'],
    secondaryItems: [
      'Provider permission',
      'Delete artifacts',
      'Delete account',
    ],
    actions: ['Export data', 'Review consent'],
  ),
  DesignScreenDefinition(
    id: 'notification-center',
    className: 'NotificationCenterDesignScreen',
    category: 'Settings',
    icon: Icons.notifications_none_rounded,
    subtitle: 'Collect macro updates, contest results, and reminders.',
    kind: DesignPreviewKind.list,
    primaryItems: [
      'Travel outlook changed',
      'Daily contest complete',
      'Follow-up reminder',
    ],
    secondaryItems: ['Unread filter', 'Notification settings'],
    actions: ['Mark all read', 'Open settings'],
  ),
  DesignScreenDefinition(
    id: 'help-safety',
    className: 'HelpSafetyDesignScreen',
    category: 'Settings',
    icon: Icons.health_and_safety_outlined,
    subtitle: 'Explain limitations and point users toward qualified support.',
    kind: DesignPreviewKind.detail,
    primaryItems: [
      'AI limitations',
      'Workplace escalation',
      'Immediate safety',
    ],
    secondaryItems: ['Legal resources', 'Mental-health support', 'Contact'],
    actions: ['Find support', 'Read limitations'],
  ),
];

DesignScreenDefinition? designScreenDefinitionById(String id) {
  for (final definition in designScreenDefinitions) {
    if (definition.id == id) return definition;
  }
  return null;
}
